### ISSUE TITLE
[Feature 1] Account Manager 

### ISSUE THREAD

**Issue by BYT18** [CSC207-2022F-UofT/course-project-project-goddid#1]
Scenario Walkthrough: Every user can either create a professional account, used to connect with others users
who are associated to their profession, or create a normal use account to connect with any individual in their list
of contacts. Besides from creating new accounts, users can delete their account and edit their personal
information. The 2 graphs will be made to manage the 2 different accounts and will keep track of each user’s
contacts (each represented by a vertex in the graph) in the form of each vertices neighbour.

**Comment by Asr161** [comment]
**Scenario Walkthrough:** Every user can either create a professional account, used to connect with others users
who are associated to their profession, or create a normal use account to connect with any individual in their list
of contacts. Besides from creating new accounts, users can delete their account and edit their personal
information. The 2 graphs will be made to manage the 2 different accounts and will keep track of each user’s
contacts (each represented by a vertex in the graph) in the form of each vertices neighbor.
