### ISSUE TITLE
[Feature 4] Point Manager

### ISSUE THREAD

**Issue by Manit2210** [CSC207-2022F-UofT/course-project-project-goddid#3]
Each time a chat ends, the details pertaining to the gaming and streak behavior associated for that chat are used to calculate the points for both the users. Each user’s profile in the PointsSystem (persistence mech) is then updated to include the new points. Provided a user has enough points (thresholds and scoring criteria tbd), they can decide to spend them via the methods mentioned in the PointSpender class. Expenditure also results in the user’s PointsSystem profile being updated.

**Comment by Jangalang2911** [comment]
Each time a chat ends, the details pertaining to the gaming and streak behavior associated for that chat are used to calculate the points for both the users. Each user’s profile in the PointsSystem (persistence mech) is then updated to include the new points. Provided a user has enough points (thresholds and scoring criteria tbd), they can decide to spend them via the methods mentioned in the PointSpender class. Expenditure also results in the user’s PointsSystem profile being updated.
